
## Spring Boot Docker Compose
spring:
  docker:
    compose:
      file: './seat-reservation/docker-compose.yaml'
  liquibase:
    contexts: '${spring.profiles.active}'



reservation:
  date:
    date-format: 'dd-MM-yyyy'