## Spring Boot Docker Compose
spring:
  datasource:
    url: jdbc:postgresql://localhost:24881/resdb
    username: resdb
    password: resdb
  jpa:
    show-sql: true
  docker:
    compose:
      file: './seat-reservation/docker-compose.yaml'
  liquibase:
    contexts: '${spring.profiles.active}'



reservation:
  date:
    date-format: 'dd-MM-yyyy'
  seat-lock:
    expiration-time: 20m
    scheduler: '0 0/10 * * * ?' # Run scheduler job every 10 minutes
  payment:
    types:
      stripe:
        successful-payment-status: 'succeeded'
