apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-service-config
data:
  spring.datasource.url: "jdbc:postgresql://postgres:5432/resdb"
  reservation.payment.types.stripe.url: 'http://payment-service:8095/v1/payment/intent'
  SPRING_PROFILES_ACTIVE: "test, prod"