apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: mrozowski/payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8095
          envFrom:
            - configMapRef:
                name: payment-service-config

