apiVersion: v1
kind: Service
metadata:
  name: reservation-frontend
spec:
  type: ClusterIP
  selector:
    app: reservation-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
