services:
  postgres:
    image: 'postgres:12'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-resdb}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-resdb}'
      - 'POSTGRES_USER=${POSTGRES_USER:-resdb}'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '${POSTGRES_PORT:-24881}:5432'
    volumes:
      - postgres-storage:/var/lib/postgresql/data
volumes:
  postgres-storage:
